[phases.setup]
nixPkgsCommit = "nixos-23.11"
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && python init_database.py && uvicorn main:app --host 0.0.0.0 --port $PORT"

[environment]
PATH = "/opt/venv/bin:$PATH" 