# Disable nixpacks to force Dockerfile usage
[config]
disabled = true

[build]
# Re-enable Nixpacks auto-detection
# disabled = true

[start]
# Use our custom server instead of default static serving
cmd = "node server.js"

[install]
# disabled = true 