[build]
# Skip React build for testing - just install deps
cmd = "echo 'Skipping React build for test'"

[start]
# Use test server to isolate the issue
cmd = "node test-server.js"

[install]
# Use npm to install dependencies
cmd = "npm install" 