[build]
# Enable build process for React app
cmd = "npm run build"

[start]
# Use our custom server instead of default static serving
cmd = "node server.js"

[install]
# Use npm to install dependencies
cmd = "npm install" 