[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx serve -s build -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "hub-frontend" 