[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]
aptPkgs = ["python3-venv"]

[phases.install]
cmds = [
  "chmod +x setup.sh",
  "./setup.sh",
  "python -m venv .venv",
  "source .venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT" 